### ISSUE TITLE
Not translating cinematic white text 

### ISSUE THREAD

**Issue by NobeUnited** [lokinmodar/Echoglossian#6] opened 2021-09-12 16:14 UTC
Would be fine if it could translate the cinematics. Like each team you enter a map the narrator says things in a white characters.

GReat job anyway dude :D

**Comment by lokinmodar** [comment] 2021-09-12 16:30
Thank you for the feedback. This is a Duplicate of issue #5 
See my last comment in there <3

**Closed by lokinmodar** 2021-09-12 16:30 UTC
